container:
  image: rust:latest

test_task:
  env:
    RUST_BACKTRACE: 1
  cargo_cache:
    folder: $CARGO_HOME/registry
    fingerprint_script: cat Cargo.lock
  before_build_script: if [[ "$OS" == "linux" ]]; then apt-get update -y && apt-get install -y libasound2-dev; fi
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $CARGO_HOME/registry/index
